import { PlantModelId, OptimalProfile } from '../types/pid';

export const OPTIMAL_PROFILES_BY_PLANT: Record<PlantModelId, OptimalProfile[]> = {
  drone: [
    {
      id: 'golden',
      name: '추천 골든 밸런스 (Golden Optimal)',
      tag: '표준 최적',
      badgeColor: 'text-amber-300 bg-amber-500/10 border-amber-500/30',
      description: '중력 가속도를 완벽히 상쇄하고 1.2초 만에 상승하여 오버슈트 2% 미만으로 정착합니다.',
      whyOptimal: '중력(-9.8m/s²)에 맞서 Ki(적분)가 기본 추력을 바쳐주고, Kd(미분)가 수직 관성을 정확히 제동합니다.',
      params: { kp: 6.5, ki: 2.2, kd: 4.8 },
      expectedResult: {
        riseTime: '1.2초',
        overshoot: '1.8%',
        settlingTime: '2.1초',
        stability: '매우 우수 (A+)',
      },
    },
    {
      id: 'agile',
      name: '고속 레이싱 반응형 (Agile Speed)',
      tag: '초고속 기동',
      badgeColor: 'text-cyan-300 bg-cyan-500/10 border-cyan-500/30',
      description: '목표 고도까지 0.8초 만에 솟구치며 약간의 오버슈트를 허용하는 민첩한 비행 세팅입니다.',
      whyOptimal: 'Kp를 높여 초기 추력을 최대화하고 레이싱 드론처럼 즉각적인 고도 변환을 수행합니다.',
      params: { kp: 9.0, ki: 3.0, kd: 3.8 },
      expectedResult: {
        riseTime: '0.8초',
        overshoot: '8.4%',
        settlingTime: '2.4초',
        stability: '양호 (A)',
      },
    },
    {
      id: 'smooth',
      name: '무오버슈트 승차감형 (Smooth Hover)',
      tag: '0% 오버슈트',
      badgeColor: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
      description: '승객이나 짐벌 카메라에 충격이 없도록 목표 고도를 단 1cm도 넘지 않는 임계 감쇠 곡선입니다.',
      whyOptimal: '고감쇠 Kd를 적용하여 목표치 직전에서 부드럽게 감속하여 오버슈트를 0%로 차단합니다.',
      params: { kp: 4.5, ki: 1.5, kd: 5.5 },
      expectedResult: {
        riseTime: '1.8초',
        overshoot: '0.0%',
        settlingTime: '2.5초',
        stability: '최고 안정 (A+)',
      },
    },
    {
      id: 'robust',
      name: '돌풍 외란 극복형 (Gust Rejection)',
      tag: '강인 제어',
      badgeColor: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
      description: '하향 돌풍(-15N)이 발생해도 고도 처짐을 즉시 감지하여 원위치로 복귀합니다.',
      whyOptimal: '높은 Ki와 강한 Kp의 결합으로 외력으로 인한 고도 이탈을 1초 내에 능동 복구합니다.',
      params: { kp: 8.0, ki: 4.5, kd: 5.2 },
      expectedResult: {
        riseTime: '1.0초',
        overshoot: '4.2%',
        settlingTime: '1.9초',
        stability: '외란 저항 탁월',
      },
    },
  ],

  car: [
    {
      id: 'golden',
      name: '추천 컴포트 주행 (Comfort Cruise)',
      tag: '표준 최적',
      badgeColor: 'text-amber-300 bg-amber-500/10 border-amber-500/30',
      description: '승객 쏠림 없이 3.2초 만에 목표 속도(80km/h)에 매끄럽게 안착합니다.',
      whyOptimal: '1.2톤 차체 관성과 공기 저항을 고려하여 스로틀 급조작 없이 부드럽게 가속합니다.',
      params: { kp: 3.2, ki: 0.8, kd: 0.6 },
      expectedResult: {
        riseTime: '3.2초',
        overshoot: '1.5%',
        settlingTime: '4.5초',
        stability: '매우 우수 (A+)',
      },
    },
    {
      id: 'sport',
      name: '스포트 다이내믹형 (Sport Mode)',
      tag: '신속 가속',
      badgeColor: 'text-cyan-300 bg-cyan-500/10 border-cyan-500/30',
      description: '스로틀을 100% 개방하여 최단 시간(1.9초)에 목표 속도에 도달합니다.',
      whyOptimal: '높은 Kp로 초기 가속력을 극대화하여 스포츠카다운 빠른 속도 추종을 구현합니다.',
      params: { kp: 5.0, ki: 1.5, kd: 0.4 },
      expectedResult: {
        riseTime: '1.9초',
        overshoot: '6.5%',
        settlingTime: '3.8초',
        stability: '양호 (A)',
      },
    },
    {
      id: 'eco',
      name: '연비 절약 에코 주행 (Eco Smooth)',
      tag: '연비 극대화',
      badgeColor: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
      description: '급가속을 억제하고 스로틀을 부드럽게 열어 연료 소비를 최소화합니다.',
      whyOptimal: '낮은 Kp와 완만한 Ki로 급출발을 방지하고 목표 속도에 오버슈트 없이 진입합니다.',
      params: { kp: 2.0, ki: 0.4, kd: 0.8 },
      expectedResult: {
        riseTime: '4.8초',
        overshoot: '0.0%',
        settlingTime: '5.6초',
        stability: '최고 부드러움',
      },
    },
    {
      id: 'hill',
      name: '급경사 오르막 극복형 (Hill Climbing)',
      tag: '경사로 보상',
      badgeColor: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
      description: '8% 급경사 오르막길에서도 속도 저하 없이 정속 주행을 유지합니다.',
      whyOptimal: '중력 감속 저항을 Ki가 즉각 감지하여 추가 엔진 토크를 빈틈없이 보상합니다.',
      params: { kp: 4.2, ki: 1.8, kd: 0.7 },
      expectedResult: {
        riseTime: '2.5초',
        overshoot: '3.0%',
        settlingTime: '3.9초',
        stability: '등판력 우수',
      },
    },
  ],

  tank: [
    {
      id: 'golden',
      name: '추천 수위 안정형 (Level Golden)',
      tag: '표준 최적',
      badgeColor: 'text-amber-300 bg-amber-500/10 border-amber-500/30',
      description: '바닥 토리첼리 유출 저항을 상쇄하며 오버슈트 2% 미만으로 정밀 유지합니다.',
      whyOptimal: '수위가 높아질수록 커지는 배수 압력에 맞춰 Ki가 펌프 기본 유량을 정밀 조율합니다.',
      params: { kp: 2.8, ki: 0.45, kd: 1.2 },
      expectedResult: {
        riseTime: '2.6초',
        overshoot: '1.9%',
        settlingTime: '4.1초',
        stability: '매우 우수 (A+)',
      },
    },
    {
      id: 'anti_spill',
      name: '넘침 방지 무오버슈트형 (Zero Spillover)',
      tag: '화학/위험물 보호',
      badgeColor: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
      description: '위험 액체가 탱크 밖으로 1방울도 넘치지 않도록 0% 오버슈트로 안착시킵니다.',
      whyOptimal: '높은 Kd의 유체 제동 효과로 목표 수위 직전에서 펌프 유량을 차단합니다.',
      params: { kp: 1.8, ki: 0.25, kd: 2.0 },
      expectedResult: {
        riseTime: '4.0초',
        overshoot: '0.0%',
        settlingTime: '4.8초',
        stability: '완전 무오버슈트',
      },
    },
    {
      id: 'rapid_fill',
      name: '급속 급수/배수형 (Fast Pumping)',
      tag: '고속 유량',
      badgeColor: 'text-cyan-300 bg-cyan-500/10 border-cyan-500/30',
      description: '공정 전환 시 최단 시간(1.6초)에 목표 수위로 탱크를 채웁니다.',
      whyOptimal: '펌프 최대 출력을 신속히 끌어내어 비어있는 탱크를 초고속 충전합니다.',
      params: { kp: 4.5, ki: 0.8, kd: 0.9 },
      expectedResult: {
        riseTime: '1.6초',
        overshoot: '7.8%',
        settlingTime: '3.4초',
        stability: '고속 반응',
      },
    },
    {
      id: 'leak_guard',
      name: '누수 외란 대응형 (Leak Resilient)',
      tag: '비상 누수 방어',
      badgeColor: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
      description: '배수 밸브 고장으로 누수가 발생해도 수위가 떨어지지 않게 펌프가 자동 증량합니다.',
      whyOptimal: '누수로 인한 지속적인 오차를 적분기(Ki)가 빠르게 인지하여 추가 급수합니다.',
      params: { kp: 3.6, ki: 1.2, kd: 1.4 },
      expectedResult: {
        riseTime: '2.1초',
        overshoot: '3.2%',
        settlingTime: '3.6초',
        stability: '누수 극복 탁월',
      },
    },
  ],

  temperature: [
    {
      id: 'golden',
      name: '추천 정밀 열처리형 (Thermal Golden)',
      tag: '표준 최적',
      badgeColor: 'text-amber-300 bg-amber-500/10 border-amber-500/30',
      description: '챔버 열용량의 긴 시간 지연(Dead-time)을 선행 제어하여 0.8% 극소 오버슈트를 달성합니다.',
      whyOptimal: '히터 열 전달 지연을 Kd가 미리 억제하여 시료의 열 충격을 예방합니다.',
      params: { kp: 4.5, ki: 0.15, kd: 6.0 },
      expectedResult: {
        riseTime: '2.8초',
        overshoot: '0.8%',
        settlingTime: '3.9초',
        stability: '매우 우수 (A+)',
      },
    },
    {
      id: 'zero_overshoot',
      name: '시료 보호 0% 오버슈트형 (Zero Burn)',
      tag: '반도체/바이오 시료',
      badgeColor: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
      description: '목표 온도를 단 0.1°C라도 넘기면 타버리는 민감한 시료 전용 0% 오버슈트 튜닝입니다.',
      whyOptimal: '강한 미분 제동(Kd=8.0)으로 목표 온도 직전에서 히터 전력을 완벽히 컷오프합니다.',
      params: { kp: 3.0, ki: 0.08, kd: 8.0 },
      expectedResult: {
        riseTime: '4.2초',
        overshoot: '0.0%',
        settlingTime: '4.9초',
        stability: '절대 안전 보장',
      },
    },
    {
      id: 'fast_heat',
      name: '초고속 예열 모드 (Rapid Preheating)',
      tag: '급속 가열',
      badgeColor: 'text-cyan-300 bg-cyan-500/10 border-cyan-500/30',
      description: '작업 시작 전 챔버를 100% 히터 전력으로 최단 시간(1.8초)에 목표 온도로 올립니다.',
      whyOptimal: '높은 Kp로 초기 통전량을 최대화하여 챔버 내부를 급속 승온시킵니다.',
      params: { kp: 7.0, ki: 0.3, kd: 4.5 },
      expectedResult: {
        riseTime: '1.8초',
        overshoot: '5.8%',
        settlingTime: '3.5초',
        stability: '가열 속도 최상',
      },
    },
    {
      id: 'door_recover',
      name: '문 개방 열손실 복구형 (Door Open Recovery)',
      tag: '외기 유입 보상',
      badgeColor: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
      description: '챔버 문이 열려 차가운 외기가 들어와도 온도가 식지 않고 강력히 재가열합니다.',
      whyOptimal: '높은 Ki(적분 게인)가 열손실 누적 오차를 즉각적으로 히터 출력으로 환산합니다.',
      params: { kp: 5.5, ki: 0.45, kd: 7.0 },
      expectedResult: {
        riseTime: '2.2초',
        overshoot: '2.1%',
        settlingTime: '3.2초',
        stability: '외란 회복 우수',
      },
    },
  ],

  pendulum: [
    {
      id: 'golden',
      name: '추천 수직 기립 골든 (Inverted Golden)',
      tag: '표준 최적',
      badgeColor: 'text-amber-300 bg-amber-500/10 border-amber-500/30',
      description: '본질적으로 불안정한 진자를 0.0° 수직으로 정확하게 세우는 최적 밸런싱입니다.',
      whyOptimal: '비선형 중력 역학에 맞서 미세 기울기에도 신속히 카트 가속력을 생성하여 지지합니다.',
      params: { kp: 18.0, ki: 1.5, kd: 7.5 },
      expectedResult: {
        riseTime: '0.6초',
        overshoot: '3.2%',
        settlingTime: '1.5초',
        stability: '매우 우수 (A+)',
      },
    },
    {
      id: 'stiff',
      name: '초강성 즉각 복원형 (Stiff Balance)',
      tag: '초고강성',
      badgeColor: 'text-cyan-300 bg-cyan-500/10 border-cyan-500/30',
      description: '0.1도의 미세한 흔들림도 용납하지 않고 단단하게 버티는 강성 튜닝입니다.',
      whyOptimal: '높은 Kp=24와 Kd=9로 진자가 흔들릴 틈 없이 카트가 즉시 하부를 받쳐줍니다.',
      params: { kp: 24.0, ki: 2.5, kd: 9.0 },
      expectedResult: {
        riseTime: '0.4초',
        overshoot: '4.8%',
        settlingTime: '1.2초',
        stability: '초고속 복원',
      },
    },
    {
      id: 'gentle',
      name: '부드러운 카트 제어형 (Gentle Cart)',
      tag: '모터 보호',
      badgeColor: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
      description: '카트의 좌우 이동 폭을 줄이고 모터 과부하를 방지하는 에너지 절약 튜닝입니다.',
      whyOptimal: '적당한 게인으로 카트 액추에이터의 전류 소모를 낮추며 부드럽게 균형을 잡습니다.',
      params: { kp: 14.0, ki: 0.8, kd: 6.5 },
      expectedResult: {
        riseTime: '0.9초',
        overshoot: '1.2%',
        settlingTime: '1.8초',
        stability: '안정 기립',
      },
    },
    {
      id: 'nudge_reject',
      name: '충격 넛지 버팀형 (Tap Rejection)',
      tag: '외력 충격 방어',
      badgeColor: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
      description: '외부에서 막대를 툭 치는 충격이 가해져도 쓰러지지 않고 원위치로 바로잡습니다.',
      whyOptimal: '충격 순간 급증하는 각속도를 높은 Kd가 억제하고 적분기가 카트를 이동시켜 복귀합니다.',
      params: { kp: 22.0, ki: 3.0, kd: 8.5 },
      expectedResult: {
        riseTime: '0.5초',
        overshoot: '2.5%',
        settlingTime: '1.4초',
        stability: '충격 내성 최고',
      },
    },
  ],

  motor: [
    {
      id: 'golden',
      name: '추천 고정밀 서보 위치 제어 (Servo Golden)',
      tag: '표준 최적',
      badgeColor: 'text-amber-300 bg-amber-500/10 border-amber-500/30',
      description: '0.1도 이내 정밀 지향 및 기계 마찰 극복, 오버슈트 1.5% 미만으로 정착합니다.',
      whyOptimal: '모터 역기전력(Back-EMF)과 회전자 관성을 계산하여 정확한 감속 브레이크를 겁니다.',
      params: { kp: 0.85, ki: 0.12, kd: 0.22 },
      expectedResult: {
        riseTime: '0.7초',
        overshoot: '1.4%',
        settlingTime: '1.3초',
        stability: '매우 우수 (A+)',
      },
    },
    {
      id: 'speed_pnp',
      name: '고속 픽앤플레이스형 (High-Speed PnP)',
      tag: '초고속 이송',
      badgeColor: 'text-cyan-300 bg-cyan-500/10 border-cyan-500/30',
      description: '반도체 마운터 로봇처럼 0.4초 만에 목표 각도로 회전하는 초고속 위치 결정입니다.',
      whyOptimal: '최대 전압(24V)을 신속히 인가하여 모터 토크를 순간적으로 끌어올립니다.',
      params: { kp: 1.3, ki: 0.2, kd: 0.18 },
      expectedResult: {
        riseTime: '0.4초',
        overshoot: '6.2%',
        settlingTime: '1.1초',
        stability: '고속 타격',
      },
    },
    {
      id: 'smooth_cnc',
      name: '무진동 정밀 가공형 (No Oscillation CNC)',
      tag: '표면 조도 최상',
      badgeColor: 'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
      description: '공작기계 가공 시 툴 떨림이 전혀 없도록 0% 오버슈트로 부드럽게 위치 결정합니다.',
      whyOptimal: '높은 제동비(Kd=0.28)로 모터 정지 시 미세 잔류 진동을 완벽히 흡수합니다.',
      params: { kp: 0.6, ki: 0.06, kd: 0.28 },
      expectedResult: {
        riseTime: '1.1초',
        overshoot: '0.0%',
        settlingTime: '1.5초',
        stability: '절대 무진동',
      },
    },
    {
      id: 'heavy_load',
      name: '고부하 토크 보상형 (Heavy Load Resilient)',
      tag: '외란 토크 방어',
      badgeColor: 'text-purple-300 bg-purple-500/10 border-purple-500/30',
      description: '출력 축에 무거운 툴이나 외력 마찰이 걸려도 각도 밀림 없이 버텨냅니다.',
      whyOptimal: '적분 게인(Ki=0.35)이 부하로 인한 미세 각도 오차를 지속적으로 상쇄합니다.',
      params: { kp: 1.1, ki: 0.35, kd: 0.25 },
      expectedResult: {
        riseTime: '0.6초',
        overshoot: '2.8%',
        settlingTime: '1.2초',
        stability: '부하 저항 탁월',
      },
    },
  ],
};
