import { PIDParameters, PlantConfig } from '../types/pid';

export interface CodeTemplate {
  language: string;
  filename: string;
  code: string;
  instructions: string;
}

export function generateAllCodeTemplates(params: PIDParameters, plant: PlantConfig): Record<string, CodeTemplate> {
  const { kp, ki, kd, filterN, antiWindup, derivativeMode, kw, b, c, outMin, outMax, dt } = params;

  // 1. C++ Header & Implementation
  const cppCode = `/**
 * @file PIDController.hpp
 * @brief Industrial PID Controller with Anti-Windup & Derivative Filter
 * Generated by PID Simulator Lab for ${plant.name}
 */

#ifndef PID_CONTROLLER_HPP
#define PID_CONTROLLER_HPP

#include <algorithm>
#include <cmath>

class PIDController {
public:
    struct Config {
        double kp = ${kp};
        double ki = ${ki};
        double kd = ${kd};
        double filterN = ${filterN}; // Derivative filter coefficient
        double outMin = ${outMin};
        double outMax = ${outMax};
        double dt = ${dt}; // Sample time in seconds
        double b = ${b}; // Setpoint weight for P
        double c = ${c}; // Setpoint weight for D
        double kw = ${kw}; // Back-calculation gain
    };

    explicit PIDController(const Config& config = Config())
        : cfg_(config), integral_(0.0), prevError_(0.0), prevMeasurement_(0.0),
          derivativeFiltered_(0.0), prevOutput_(0.0) {}

    void reset(double initialPv = 0.0) {
        integral_ = 0.0;
        prevError_ = 0.0;
        prevMeasurement_ = initialPv;
        derivativeFiltered_ = 0.0;
        prevOutput_ = 0.0;
    }

    void updateParams(double kp, double ki, double kd) {
        cfg_.kp = kp;
        cfg_.ki = ki;
        cfg_.kd = kd;
    }

    double compute(double setpoint, double measurement, double dtOverride = -1.0) {
        const double dt = (dtOverride > 0.0) ? dtOverride : cfg_.dt;
        const double error = setpoint - measurement;
        const double pError = cfg_.b * setpoint - measurement;

        // 1. Proportional Term
        const double pTerm = cfg_.kp * pError;

        // 2. Derivative Term with Filtering (on ${derivativeMode === 'on_measurement' ? 'Measurement' : 'Error'})
        ${derivativeMode === 'on_measurement'
          ? 'const double dInput = -(measurement - prevMeasurement_);'
          : 'const double dInput = (cfg_.c * setpoint - measurement) - (cfg_.c * setpoint - prevMeasurement_);'}
        
        const double Tf = (cfg_.kp > 1e-4) ? std::max(0.001, cfg_.kd / (cfg_.kp * std::max(1.0, cfg_.filterN))) : 0.05;
        const double alpha = Tf / (Tf + dt);
        const double rawD = cfg_.kd * (dInput / dt);
        derivativeFiltered_ = alpha * derivativeFiltered_ + (1.0 - alpha) * rawD;
        const double dTerm = derivativeFiltered_;

        // 3. Candidate Integral
        const double candidateIntegral = integral_ + cfg_.ki * error * dt;
        const double uUnsat = pTerm + candidateIntegral + dTerm;

        // 4. Output Saturation & Anti-Windup (${antiWindup})
        double uSat = std::clamp(uUnsat, cfg_.outMin, cfg_.outMax);

        ${antiWindup === 'clamping' ? `// Clamping anti-windup
        bool satHigh = (uUnsat > cfg_.outMax) && (error > 0.0);
        bool satLow = (uUnsat < cfg_.outMin) && (error < 0.0);
        if (!satHigh && !satLow) {
            integral_ = candidateIntegral;
        }` : antiWindup === 'back-calculation' ? `// Back-calculation anti-windup
        integral_ += (cfg_.ki * error + cfg_.kw * (uSat - uUnsat)) * dt;` : `// No anti-windup
        integral_ = candidateIntegral;`}

        // Bound integral buffer
        const double maxInt = (cfg_.outMax - cfg_.outMin) * 3.0;
        integral_ = std::clamp(integral_, -maxInt, maxInt);

        prevError_ = error;
        prevMeasurement_ = measurement;
        prevOutput_ = uSat;

        return uSat;
    }

private:
    Config cfg_;
    double integral_;
    double prevError_;
    double prevMeasurement_;
    double derivativeFiltered_;
    double prevOutput_;
};

#endif // PID_CONTROLLER_HPP
`;

  // 2. Python Class & Simulation Script
  const pyCode = `#!/usr/bin/env python3
"""
PID Controller Module with Anti-Windup & Derivative Filter
Target System: ${plant.name}
Generated by PID Simulator Lab
"""

import numpy as np

class PIDController:
    def __init__(self,
                 kp: float = ${kp},
                 ki: float = ${ki},
                 kd: float = ${kd},
                 filter_n: float = ${filterN},
                 out_min: float = ${outMin},
                 out_max: float = ${outMax},
                 dt: float = ${dt},
                 anti_windup: str = '${antiWindup}',
                 derivative_mode: str = '${derivativeMode}',
                 b: float = ${b},
                 c: float = ${c},
                 kw: float = ${kw}):
        self.kp = kp
        self.ki = ki
        self.kd = kd
        self.filter_n = filter_n
        self.out_min = out_min
        self.out_max = out_max
        self.dt = dt
        self.anti_windup = anti_windup
        self.derivative_mode = derivative_mode
        self.b = b
        self.c = c
        self.kw = kw

        self.reset()

    def reset(self, initial_pv: float = 0.0):
        self.integral = 0.0
        self.prev_error = 0.0
        self.prev_measurement = initial_pv
        self.derivative_filtered = 0.0
        self.prev_output = 0.0

    def compute(self, setpoint: float, measurement: float, dt: float = None) -> float:
        dt = dt if (dt is not None and dt > 0) else self.dt
        error = setpoint - measurement
        p_error = self.b * setpoint - measurement

        # 1. Proportional Term
        p_term = self.kp * p_error

        # 2. Derivative Term with LPF
        if self.derivative_mode == 'on_measurement':
            d_input = -(measurement - self.prev_measurement)
        else:
            d_input = (self.c * setpoint - measurement) - (self.c * setpoint - self.prev_measurement)

        tf = max(0.001, self.kd / (self.kp * max(1.0, self.filter_n))) if self.kp > 1e-4 else 0.05
        alpha = tf / (tf + dt)
        raw_d = self.kd * (d_input / dt)
        self.derivative_filtered = alpha * self.derivative_filtered + (1.0 - alpha) * raw_d
        d_term = self.derivative_filtered

        # 3. Integral Candidate
        candidate_integral = self.integral + self.ki * error * dt
        u_unsat = p_term + candidate_integral + d_term

        # 4. Saturation & Anti-Windup
        u_sat = max(self.out_min, min(self.out_max, u_unsat))

        if self.anti_windup == 'clamping':
            sat_high = (u_unsat > self.out_max) and (error > 0)
            sat_low = (u_unsat < self.out_min) and (error < 0)
            if not (sat_high or sat_low):
                self.integral = candidate_integral
        elif self.anti_windup == 'back-calculation':
            self.integral += (self.ki * error + self.kw * (u_sat - u_unsat)) * dt
        else:
            self.integral = candidate_integral

        max_int = (self.out_max - self.out_min) * 3.0
        self.integral = max(-max_int, min(max_int, self.integral))

        self.prev_error = error
        self.prev_measurement = measurement
        self.prev_output = u_sat
        return u_sat

if __name__ == "__main__":
    pid = PIDController()
    target = ${plant.setpointDefault}
    pv = 0.0
    print(f"Starting PID simulation for target {target} {plant.unit}...")
    for step in range(50):
        u = pid.compute(target, pv)
        # Toy plant step response
        pv += (u * 0.1 - pv * 0.05) * pid.dt
        if step % 10 == 0:
            print(f"t={step*pid.dt:.2f}s | PV={pv:.2f} | Out={u:.2f}")
`;

  // 3. Arduino / Microcontroller C++ Sketch
  const arduinoCode = `/**
 * Arduino / ESP32 PID Firmware
 * System: ${plant.name}
 * Generated by PID Simulator Lab
 */

// Controller Parameters
const float Kp = ${kp}f;
const float Ki = ${ki}f;
const float Kd = ${kd}f;
const float FilterN = ${filterN}f;
const float OutMin = ${outMin}f;
const float OutMax = ${outMax}f;
const float SampleTimeSec = ${dt}f; // ${(dt * 1000).toFixed(0)} ms

float setpoint = ${plant.setpointDefault}f;
float currentPv = 0.0f;

// PID Internal States
float integral = 0.0f;
float prevMeasurement = 0.0f;
float derivativeFiltered = 0.0f;
unsigned long lastSampleMillis = 0;

float computePID(float sp, float pv, float dt) {
  float error = sp - pv;
  
  // Proportional
  float pTerm = Kp * error;
  
  // Derivative on measurement (prevents derivative kick)
  float dInput = -(pv - prevMeasurement);
  float Tf = (Kp > 0.001f) ? (Kd / (Kp * FilterN)) : 0.05f;
  float alpha = Tf / (Tf + dt);
  float rawD = Kd * (dInput / dt);
  derivativeFiltered = alpha * derivativeFiltered + (1.0f - alpha) * rawD;
  float dTerm = derivativeFiltered;
  
  // Integral candidate
  float candidateIntegral = integral + Ki * error * dt;
  float uUnsat = pTerm + candidateIntegral + dTerm;
  
  // Clamp & Anti-windup
  float uSat = constrain(uUnsat, OutMin, OutMax);
  bool satHigh = (uUnsat > OutMax) && (error > 0.0f);
  bool satLow = (uUnsat < OutMin) && (error < 0.0f);
  if (!satHigh && !satLow) {
    integral = candidateIntegral;
  }
  
  prevMeasurement = pv;
  return uSat;
}

void setup() {
  Serial.begin(115200);
  lastSampleMillis = millis();
}

void loop() {
  unsigned long now = millis();
  unsigned long intervalMs = (unsigned long)(SampleTimeSec * 1000.0f);

  if (now - lastSampleMillis >= intervalMs) {
    float dt = (now - lastSampleMillis) / 1000.0f;
    lastSampleMillis = now;

    // Read sensor (replace with analogRead, encoder, etc.)
    // currentPv = readSensor();

    float output = computePID(setpoint, currentPv, dt);

    // Apply to actuator (analogWrite, DAC, PWM)
    // applyActuator(output);

    Serial.print("SP:");
    Serial.print(setpoint);
    Serial.print(" PV:");
    Serial.print(currentPv);
    Serial.print(" OUT:");
    Serial.println(output);
  }
}
`;

  // 4. TypeScript / ESM Package
  const tsCode = `/**
 * Production-ready TypeScript PID Controller Package
 * System: ${plant.name}
 * Generated by PID Simulator Lab
 */

export interface PIDOptions {
  kp?: number;
  ki?: number;
  kd?: number;
  filterN?: number;
  outMin?: number;
  outMax?: number;
  dt?: number;
  antiWindup?: 'clamping' | 'back-calculation' | 'none';
  derivativeMode?: 'on_error' | 'on_measurement';
  b?: number;
  c?: number;
  kw?: number;
}

export class PIDController {
  public kp: number;
  public ki: number;
  public kd: number;
  public filterN: number;
  public outMin: number;
  public outMax: number;
  public dt: number;
  public antiWindup: 'clamping' | 'back-calculation' | 'none';
  public derivativeMode: 'on_error' | 'on_measurement';
  public b: number;
  public c: number;
  public kw: number;

  private integral = 0;
  private prevMeasurement = 0;
  private derivativeFiltered = 0;

  constructor(opts: PIDOptions = {}) {
    this.kp = opts.kp ?? ${kp};
    this.ki = opts.ki ?? ${ki};
    this.kd = opts.kd ?? ${kd};
    this.filterN = opts.filterN ?? ${filterN};
    this.outMin = opts.outMin ?? ${outMin};
    this.outMax = opts.outMax ?? ${outMax};
    this.dt = opts.dt ?? ${dt};
    this.antiWindup = opts.antiWindup ?? '${antiWindup}';
    this.derivativeMode = opts.derivativeMode ?? '${derivativeMode}';
    this.b = opts.b ?? ${b};
    this.c = opts.c ?? ${c};
    this.kw = opts.kw ?? ${kw};
  }

  public reset(initialPv = 0): void {
    this.integral = 0;
    this.prevMeasurement = initialPv;
    this.derivativeFiltered = 0;
  }

  public compute(setpoint: number, measurement: number, dtOverride?: number): number {
    const dt = dtOverride && dtOverride > 0 ? dtOverride : this.dt;
    const error = setpoint - measurement;
    const pError = this.b * setpoint - measurement;

    // 1. Proportional
    const pTerm = this.kp * pError;

    // 2. Derivative
    const dInput = this.derivativeMode === 'on_measurement'
      ? -(measurement - this.prevMeasurement)
      : (this.c * setpoint - measurement) - (this.c * setpoint - this.prevMeasurement);

    const Tf = this.kp > 1e-4 ? Math.max(0.001, this.kd / (this.kp * Math.max(1, this.filterN))) : 0.05;
    const alpha = Tf / (Tf + dt);
    const rawD = this.kd * (dInput / dt);
    this.derivativeFiltered = alpha * this.derivativeFiltered + (1 - alpha) * rawD;
    const dTerm = this.derivativeFiltered;

    // 3. Integral candidate & Saturation
    const candidateIntegral = this.integral + this.ki * error * dt;
    const uUnsat = pTerm + candidateIntegral + dTerm;
    const uSat = Math.max(this.outMin, Math.min(this.outMax, uUnsat));

    // 4. Anti-Windup
    if (this.antiWindup === 'clamping') {
      const satHigh = uUnsat > this.outMax && error > 0;
      const satLow = uUnsat < this.outMin && error < 0;
      if (!satHigh && !satLow) {
        this.integral = candidateIntegral;
      }
    } else if (this.antiWindup === 'back-calculation') {
      this.integral += (this.ki * error + this.kw * (uSat - uUnsat)) * dt;
    } else {
      this.integral = candidateIntegral;
    }

    this.prevMeasurement = measurement;
    return uSat;
  }
}
`;

  // 5. MATLAB Script
  const matlabCode = `%% PID Simulation Script for MATLAB / GNU Octave
% Target Plant: ${plant.name}
% Generated by PID Simulator Lab

clear; clc; close all;

%% Controller Parameters
Kp = ${kp};
Ki = ${ki};
Kd = ${kd};
N = ${filterN};        % Derivative filter coefficient
dt = ${dt};           % Sample time (s)
t_final = 20.0;       % Simulation duration (s)
t = 0:dt:t_final;
N_steps = length(t);

% Setpoint trajectory
SP = ${plant.setpointDefault} * ones(1, N_steps);
PV = zeros(1, N_steps);
U = zeros(1, N_steps);

u_min = ${outMin};
u_max = ${outMax};

%% State Variables
integral = 0;
prev_measurement = 0;
d_filtered = 0;
Tf = max(0.001, Kd / (Kp * N));
alpha = Tf / (Tf + dt);

%% Simulation Loop
fprintf('Simulating PID controller...\\n');
for k = 1:N_steps
    sp = SP(k);
    pv = PV(k);
    error = sp - pv;
    
    % Proportional
    p_term = Kp * error;
    
    % Derivative (on measurement)
    d_input = -(pv - prev_measurement);
    raw_d = Kd * (d_input / dt);
    d_filtered = alpha * d_filtered + (1 - alpha) * raw_d;
    d_term = d_filtered;
    
    % Integral candidate
    candidate_integral = integral + Ki * error * dt;
    u_unsat = p_term + candidate_integral + d_term;
    
    % Saturation & Clamping
    u_sat = max(u_min, min(u_max, u_unsat));
    if ~((u_unsat > u_max && error > 0) || (u_unsat < u_min && error < 0))
        integral = candidate_integral;
    end
    
    U(k) = u_sat;
    prev_measurement = pv;
    
    % Plant Euler step (approximate)
    if k < N_steps
        PV(k+1) = PV(k) + (u_sat * 0.1 - PV(k) * 0.05) * dt;
    end
end

%% Plot Results
figure('Name', 'PID Step Response', 'Color', 'w');
subplot(2,1,1);
plot(t, SP, 'r--', 'LineWidth', 1.5); hold on;
plot(t, PV, 'b-', 'LineWidth', 2);
grid on; ylabel('${plant.variableName} [${plant.unit}]');
legend('Setpoint', 'Process Variable');
title('PID Closed-Loop Response');

subplot(2,1,2);
plot(t, U, 'k-', 'LineWidth', 1.5);
grid on; xlabel('Time [s]'); ylabel('Control Output u(t)');
legend('Control Effort');
`;

  return {
    cpp: {
      language: 'C++',
      filename: 'PIDController.hpp',
      code: cppCode,
      instructions: '헤더 파일(PIDController.hpp)을 프로젝트에 복사하여 즉시 #include <PIDController.hpp> 로 사용하실 수 있습니다.',
    },
    python: {
      language: 'Python',
      filename: 'pid_controller.py',
      code: pyCode,
      instructions: 'pip 라이브러리 없이 순수 파이썬 및 NumPy로 실행 가능한 독립 모듈입니다.',
    },
    arduino: {
      language: 'Arduino / C++',
      filename: 'pid_firmware.ino',
      code: arduinoCode,
      instructions: 'Arduino IDE, PlatformIO, ESP32, STM32에서 바로 업로드하여 하드웨어 제어에 활용할 수 있습니다.',
    },
    typescript: {
      language: 'TypeScript / Node.js',
      filename: 'pidController.ts',
      code: tsCode,
      instructions: 'Node.js 백엔드 서버, React/Vue 클라이언트 및 임베디드 JS 런타임에서 import하여 사용할 수 있습니다.',
    },
    matlab: {
      language: 'MATLAB / Octave',
      filename: 'pid_simulation.m',
      code: matlabCode,
      instructions: 'MATLAB 또는 무료 오픈소스 GNU Octave에서 스크립트를 바로 실행하여 응답 곡선을 확인하세요.',
    },
  };
}
